algoritmo "SOMAPARAMETROSREFERENCIA"
var
   X, Y:Inteiro
Procedimento Soma (Var A, B:Inteiro)
inicio
      A <- A + 1
      B <- B + 2
      Escreval ("Valor de A = ", A)
      Escreval ("Valor de B = ", B)
      Escreval ("Soma de A + B = ", A+B)
Fimprocedimento
inicio
      X <- 4
      Y <- 8
      Soma (X, y)
      Escreval("Valor de X = ",X)
      Escreval("Valor de Y = ",Y)
fimalgoritmo